//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDB
    {
        public int IdEmployee { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public int idCompany { get; set; }
    
        public virtual CompaniesDB CompaniesDB { get; set; }
        public virtual EmplyeeInfoDB EmplyeeInfoDB { get; set; }
    }
}
